# Generated by ASRtools (0.1.2): do not edit by hand!!!
# Please edit source code in R-autoFunction/prepare-acdc-covars.R
.prepare_acdc_covars<-function(...){
expression(covars.type <- ifelse(pedometrics::is.any.factor(covars), "factor", "numeric"), 
    if (use.coords) {
      covars <- data.frame(covars, candi[, 2:3])
    }, if (covars.type == "factor") {
      
      # Convert numeric covariates to factor covariates
      if (!pedometrics::is.all.factor(covars)) {
        i <- which(sapply(covars, is.factor) == FALSE)
        mes <- paste("converting ", length(i), 
                     " numeric covariates to factor covariates", sep = "")
        message(mes)
        num_covars <- data.frame(covars[, i])
        breaks <- .numStrata(n.pts = n_pts, covars = num_covars, 
                             strata.type = strata.type)[[1]]
        num_covars <- pedometrics::cont2cat(x = num_covars, breaks = breaks)
        covars[, i] <- num_covars
      }
    }, n_cov <- ncol(covars), sm <- covars[points[, 1], ])
}

