# Generated by ASRtools (0.1.2): do not edit by hand!!!
# Please edit source code in R-autoFunction/prepare-jittering.R
.prepare_jittering<-function(...){
expression(if (missing(x.min) && missing(x.max) && missing(y.min) && missing(y.max)) {
  message("estimating 'x.min', 'x.max', 'y.min', and 'y.max' from 'candi'")
  x <- SpatialTools::dist1(as.matrix(candi[, "x"]))
  id <- x > 0
  x.min <- min(x[id])
  x.max <- max(x)
  y <- SpatialTools::dist1(as.matrix(candi[, "y"]))
  id <- y > 0
  y.min <- min(y[id])
  y.max <- max(y)
}, x_max0 <- x.max, y_max0 <- y.max, rm(x, id, y))
}

