# Generated by autofun (0.0.0.9000): do not edit by hand!!!
# Please edit source code in R-autofun/prepare-points.R
.prepare_points<-function(...){
expression(if (!missing(candi)) {
  n_candi <- nrow(candi)
  candi <- as.matrix(cbind(id = 1:n_candi, candi))
}, if (is.integer(points) || is.numint(points)) {
  if (length(points) > 1) { # Integer vector
    points <- candi[points, ]
  }
  if (length(points) == 1) { # Integer value
    points <- sample(1:n_candi, points)
    points <- candi[points, ] 
  }
} else { # Data frame of matrix
  points <- points
}, n_pts <- nrow(points), conf0 <- points, old_conf <- conf0)
}

