# Generated by autofun (0.0.0.9000): do not edit by hand!!!
# Please edit source code in R-autofun/prepare-output.R
.prepare_output<-function(...){
expression(if (progress) close(pb), res <- new_conf, a <- attributes(res), 
    if (!track) energies <- new_energy, if (MOOP) {
      criterion <- rbind(energy0, energies)
    } else {
      criterion <- c(energy0, energies)
    }, a$energy.state <- criterion, a$iterations <- k, a$running.time <- round(c((proc.time() - time0) / 60)[3], 2), 
    if (MOOP) {
      a$weights <- weights
      a$nadir <- nadir
      a$utopia <- utopia
    }, attributes(res) <- a, cat("iterations = ", a$iterations, "\n", sep = ""), 
    cat("running time = ", a$running.time, " minutes", sep = ""), 
    return (res))
}

